# Generated by Django 5.0.1 on 2026-03-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('plano_individual_mensal', 'Plano individual mensal'), ('plano_individual_anual', 'Plano individual anual')], default='free', max_length=64)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('INCOMPLETE', 'Incomplete'), ('ACTIVE', 'Active'), ('TRIALING', 'Trialing'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled')], default='INACTIVE', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscription', to='accounts.user')),
            ],
            options={
                'db_table': 'accounts_user_subscription',
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['plan', 'status'], name='accounts_us_plan_9c8435_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['stripe_customer_id'], name='accounts_us_stripe__af4d45_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['stripe_subscription_id'], name='accounts_us_stripe__070eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['stripe_checkout_session_id'], name='accounts_us_stripe__e65c42_idx'),
        ),
    ]
