# Generated by Django 5.0.1 on 2026-03-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_usersubscription"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usersubscription",
            new_name="accounts_us_plan_80f9ca_idx",
            old_name="accounts_us_plan_9c8435_idx",
        ),
        migrations.RenameIndex(
            model_name="usersubscription",
            new_name="accounts_us_stripe__3999b1_idx",
            old_name="accounts_us_stripe__af4d45_idx",
        ),
        migrations.RenameIndex(
            model_name="usersubscription",
            new_name="accounts_us_stripe__fce079_idx",
            old_name="accounts_us_stripe__070eb7_idx",
        ),
        migrations.RenameIndex(
            model_name="usersubscription",
            new_name="accounts_us_stripe__94f17f_idx",
            old_name="accounts_us_stripe__e65c42_idx",
        ),
    ]
