# Generated by Django 5.0.1 on 2026-03-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_rename_accounts_us_plan_9c8435_idx_accounts_us_plan_80f9ca_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="billing_grace_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
