# Generated by Django 5.0.1 on 2026-03-09 20:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_usersubscription_billing_grace_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(choices=[("CLINIC_REMOVED", "Clinic removed")], max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="notices",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user_notice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="usernotice",
            index=models.Index(
                fields=["user", "acknowledged_at", "created_at"],
                name="accounts_us_user_id_8ec44c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usernotice",
            index=models.Index(
                fields=["type", "created_at"],
                name="accounts_us_type_1642e2_idx",
            ),
        ),
    ]
