# Generated by Django 5.0.1 on 2026-03-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_usernotice"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usernotice",
            new_name="accounts_us_user_id_0d02a1_idx",
            old_name="accounts_us_user_id_8ec44c_idx",
        ),
        migrations.RenameIndex(
            model_name="usernotice",
            new_name="accounts_us_type_607ac2_idx",
            old_name="accounts_us_type_1642e2_idx",
        ),
    ]
