# Generated by Django 5.0.1 on 2026-03-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_accounts_us_user_id_8ec44c_idx_accounts_us_user_id_0d02a1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_lifecycle_status',
            field=models.CharField(
                choices=[('active', 'Active'), ('deleted', 'Deleted')],
                default='active',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_lifecycle_status'], name='accounts_us_account_d2e0a0_idx'),
        ),
    ]
