# Generated by Django 5.0.1 on 2026-03-09 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_account_lifecycle_and_subscription_cancel_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_account_b8f1f3_idx",
            old_name="accounts_us_account_d2e0a0_idx",
        ),
    ]
