# Generated by Django 5.0.1 on 2026-02-11 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Object category selected by user", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "inference_job_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from external inference API",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "s3_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 path to final NIfTI result",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if processing failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "studies_study",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_job_id",
                    models.CharField(
                        help_text="Job ID from external inference API",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job",
                        to="studies.study",
                    ),
                ),
            ],
            options={
                "db_table": "studies_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["clinic", "owner"], name="studies_stu_clinic__d227b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(fields=["status"], name="studies_stu_status_34eaf0_idx"),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["inference_job_id"], name="studies_stu_inferen_aee16a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["external_job_id"], name="studies_job_externa_bb183c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="studies_job_status_eafa46_idx"),
        ),
    ]
