# Generated by Django 5.0.1 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="image_s3_key",
            field=models.CharField(
                blank=True,
                help_text="S3 path to image NIfTI for visualization",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="mask_s3_key",
            field=models.CharField(
                blank=True,
                help_text="S3 path to segmentation NIfTI for visualization",
                max_length=500,
                null=True,
            ),
        ),
    ]

