# Generated by Django 5.0.1 on 2026-02-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_alter_study_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Patient age in years",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="case_identification",
            field=models.CharField(
                blank=True,
                help_text="Case identifier provided by user",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="exam_modality",
            field=models.CharField(
                blank=True,
                help_text="Exam modality selected by user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="exam_source",
            field=models.CharField(
                blank=True,
                help_text="Exam source provided by user",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="patient_name",
            field=models.CharField(
                blank=True,
                help_text="Patient name provided by user",
                max_length=255,
                null=True,
            ),
        ),
    ]
