# Generated by Django 5.0.1 on 2026-03-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0004_add_study_metadata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="descriptive_analysis",
            field=models.TextField(
                blank=True,
                help_text="Cached descriptive medical analysis generated from segmentation summary",
                null=True,
            ),
        ),
    ]
