export interface CountryOption {
  code: string;
  label: string;
}

const COUNTRY_SEED: Array<{ code: string; fallbackLabel: string }> = [
  { code: "AD", fallbackLabel: "Andorra" },
  { code: "AE", fallbackLabel: "United Arab Emirates" },
  { code: "AF", fallbackLabel: "Afghanistan" },
  { code: "AG", fallbackLabel: "Antigua & Barbuda" },
  { code: "AI", fallbackLabel: "Anguilla" },
  { code: "AL", fallbackLabel: "Albania" },
  { code: "AM", fallbackLabel: "Armenia" },
  { code: "AO", fallbackLabel: "Angola" },
  { code: "AQ", fallbackLabel: "Antarctica" },
  { code: "AR", fallbackLabel: "Argentina" },
  { code: "AS", fallbackLabel: "Samoa (American)" },
  { code: "AT", fallbackLabel: "Austria" },
  { code: "AU", fallbackLabel: "Australia" },
  { code: "AW", fallbackLabel: "Aruba" },
  { code: "AX", fallbackLabel: "Åland Islands" },
  { code: "AZ", fallbackLabel: "Azerbaijan" },
  { code: "BA", fallbackLabel: "Bosnia & Herzegovina" },
  { code: "BB", fallbackLabel: "Barbados" },
  { code: "BD", fallbackLabel: "Bangladesh" },
  { code: "BE", fallbackLabel: "Belgium" },
  { code: "BF", fallbackLabel: "Burkina Faso" },
  { code: "BG", fallbackLabel: "Bulgaria" },
  { code: "BH", fallbackLabel: "Bahrain" },
  { code: "BI", fallbackLabel: "Burundi" },
  { code: "BJ", fallbackLabel: "Benin" },
  { code: "BL", fallbackLabel: "St Barthelemy" },
  { code: "BM", fallbackLabel: "Bermuda" },
  { code: "BN", fallbackLabel: "Brunei" },
  { code: "BO", fallbackLabel: "Bolivia" },
  { code: "BQ", fallbackLabel: "Caribbean NL" },
  { code: "BR", fallbackLabel: "Brazil" },
  { code: "BS", fallbackLabel: "Bahamas" },
  { code: "BT", fallbackLabel: "Bhutan" },
  { code: "BV", fallbackLabel: "Bouvet Island" },
  { code: "BW", fallbackLabel: "Botswana" },
  { code: "BY", fallbackLabel: "Belarus" },
  { code: "BZ", fallbackLabel: "Belize" },
  { code: "CA", fallbackLabel: "Canada" },
  { code: "CC", fallbackLabel: "Cocos (Keeling) Islands" },
  { code: "CD", fallbackLabel: "Congo (Dem. Rep.)" },
  { code: "CF", fallbackLabel: "Central African Rep." },
  { code: "CG", fallbackLabel: "Congo (Rep.)" },
  { code: "CH", fallbackLabel: "Switzerland" },
  { code: "CI", fallbackLabel: "Côte d’Ivoire" },
  { code: "CK", fallbackLabel: "Cook Islands" },
  { code: "CL", fallbackLabel: "Chile" },
  { code: "CM", fallbackLabel: "Cameroon" },
  { code: "CN", fallbackLabel: "China" },
  { code: "CO", fallbackLabel: "Colombia" },
  { code: "CR", fallbackLabel: "Costa Rica" },
  { code: "CU", fallbackLabel: "Cuba" },
  { code: "CV", fallbackLabel: "Cape Verde" },
  { code: "CW", fallbackLabel: "Curaçao" },
  { code: "CX", fallbackLabel: "Christmas Island" },
  { code: "CY", fallbackLabel: "Cyprus" },
  { code: "CZ", fallbackLabel: "Czech Republic" },
  { code: "DE", fallbackLabel: "Germany" },
  { code: "DJ", fallbackLabel: "Djibouti" },
  { code: "DK", fallbackLabel: "Denmark" },
  { code: "DM", fallbackLabel: "Dominica" },
  { code: "DO", fallbackLabel: "Dominican Republic" },
  { code: "DZ", fallbackLabel: "Algeria" },
  { code: "EC", fallbackLabel: "Ecuador" },
  { code: "EE", fallbackLabel: "Estonia" },
  { code: "EG", fallbackLabel: "Egypt" },
  { code: "EH", fallbackLabel: "Western Sahara" },
  { code: "ER", fallbackLabel: "Eritrea" },
  { code: "ES", fallbackLabel: "Spain" },
  { code: "ET", fallbackLabel: "Ethiopia" },
  { code: "FI", fallbackLabel: "Finland" },
  { code: "FJ", fallbackLabel: "Fiji" },
  { code: "FK", fallbackLabel: "Falkland Islands" },
  { code: "FM", fallbackLabel: "Micronesia" },
  { code: "FO", fallbackLabel: "Faroe Islands" },
  { code: "FR", fallbackLabel: "France" },
  { code: "GA", fallbackLabel: "Gabon" },
  { code: "GB", fallbackLabel: "Britain (UK)" },
  { code: "GD", fallbackLabel: "Grenada" },
  { code: "GE", fallbackLabel: "Georgia" },
  { code: "GF", fallbackLabel: "French Guiana" },
  { code: "GG", fallbackLabel: "Guernsey" },
  { code: "GH", fallbackLabel: "Ghana" },
  { code: "GI", fallbackLabel: "Gibraltar" },
  { code: "GL", fallbackLabel: "Greenland" },
  { code: "GM", fallbackLabel: "Gambia" },
  { code: "GN", fallbackLabel: "Guinea" },
  { code: "GP", fallbackLabel: "Guadeloupe" },
  { code: "GQ", fallbackLabel: "Equatorial Guinea" },
  { code: "GR", fallbackLabel: "Greece" },
  { code: "GS", fallbackLabel: "South Georgia & the South Sandwich Islands" },
  { code: "GT", fallbackLabel: "Guatemala" },
  { code: "GU", fallbackLabel: "Guam" },
  { code: "GW", fallbackLabel: "Guinea-Bissau" },
  { code: "GY", fallbackLabel: "Guyana" },
  { code: "HK", fallbackLabel: "Hong Kong" },
  { code: "HM", fallbackLabel: "Heard Island & McDonald Islands" },
  { code: "HN", fallbackLabel: "Honduras" },
  { code: "HR", fallbackLabel: "Croatia" },
  { code: "HT", fallbackLabel: "Haiti" },
  { code: "HU", fallbackLabel: "Hungary" },
  { code: "ID", fallbackLabel: "Indonesia" },
  { code: "IE", fallbackLabel: "Ireland" },
  { code: "IL", fallbackLabel: "Israel" },
  { code: "IM", fallbackLabel: "Isle of Man" },
  { code: "IN", fallbackLabel: "India" },
  { code: "IO", fallbackLabel: "British Indian Ocean Territory" },
  { code: "IQ", fallbackLabel: "Iraq" },
  { code: "IR", fallbackLabel: "Iran" },
  { code: "IS", fallbackLabel: "Iceland" },
  { code: "IT", fallbackLabel: "Italy" },
  { code: "JE", fallbackLabel: "Jersey" },
  { code: "JM", fallbackLabel: "Jamaica" },
  { code: "JO", fallbackLabel: "Jordan" },
  { code: "JP", fallbackLabel: "Japan" },
  { code: "KE", fallbackLabel: "Kenya" },
  { code: "KG", fallbackLabel: "Kyrgyzstan" },
  { code: "KH", fallbackLabel: "Cambodia" },
  { code: "KI", fallbackLabel: "Kiribati" },
  { code: "KM", fallbackLabel: "Comoros" },
  { code: "KN", fallbackLabel: "St Kitts & Nevis" },
  { code: "KP", fallbackLabel: "Korea (North)" },
  { code: "KR", fallbackLabel: "Korea (South)" },
  { code: "KW", fallbackLabel: "Kuwait" },
  { code: "KY", fallbackLabel: "Cayman Islands" },
  { code: "KZ", fallbackLabel: "Kazakhstan" },
  { code: "LA", fallbackLabel: "Laos" },
  { code: "LB", fallbackLabel: "Lebanon" },
  { code: "LC", fallbackLabel: "St Lucia" },
  { code: "LI", fallbackLabel: "Liechtenstein" },
  { code: "LK", fallbackLabel: "Sri Lanka" },
  { code: "LR", fallbackLabel: "Liberia" },
  { code: "LS", fallbackLabel: "Lesotho" },
  { code: "LT", fallbackLabel: "Lithuania" },
  { code: "LU", fallbackLabel: "Luxembourg" },
  { code: "LV", fallbackLabel: "Latvia" },
  { code: "LY", fallbackLabel: "Libya" },
  { code: "MA", fallbackLabel: "Morocco" },
  { code: "MC", fallbackLabel: "Monaco" },
  { code: "MD", fallbackLabel: "Moldova" },
  { code: "ME", fallbackLabel: "Montenegro" },
  { code: "MF", fallbackLabel: "St Martin (French)" },
  { code: "MG", fallbackLabel: "Madagascar" },
  { code: "MH", fallbackLabel: "Marshall Islands" },
  { code: "MK", fallbackLabel: "North Macedonia" },
  { code: "ML", fallbackLabel: "Mali" },
  { code: "MM", fallbackLabel: "Myanmar (Burma)" },
  { code: "MN", fallbackLabel: "Mongolia" },
  { code: "MO", fallbackLabel: "Macau" },
  { code: "MP", fallbackLabel: "Northern Mariana Islands" },
  { code: "MQ", fallbackLabel: "Martinique" },
  { code: "MR", fallbackLabel: "Mauritania" },
  { code: "MS", fallbackLabel: "Montserrat" },
  { code: "MT", fallbackLabel: "Malta" },
  { code: "MU", fallbackLabel: "Mauritius" },
  { code: "MV", fallbackLabel: "Maldives" },
  { code: "MW", fallbackLabel: "Malawi" },
  { code: "MX", fallbackLabel: "Mexico" },
  { code: "MY", fallbackLabel: "Malaysia" },
  { code: "MZ", fallbackLabel: "Mozambique" },
  { code: "NA", fallbackLabel: "Namibia" },
  { code: "NC", fallbackLabel: "New Caledonia" },
  { code: "NE", fallbackLabel: "Niger" },
  { code: "NF", fallbackLabel: "Norfolk Island" },
  { code: "NG", fallbackLabel: "Nigeria" },
  { code: "NI", fallbackLabel: "Nicaragua" },
  { code: "NL", fallbackLabel: "Netherlands" },
  { code: "NO", fallbackLabel: "Norway" },
  { code: "NP", fallbackLabel: "Nepal" },
  { code: "NR", fallbackLabel: "Nauru" },
  { code: "NU", fallbackLabel: "Niue" },
  { code: "NZ", fallbackLabel: "New Zealand" },
  { code: "OM", fallbackLabel: "Oman" },
  { code: "PA", fallbackLabel: "Panama" },
  { code: "PE", fallbackLabel: "Peru" },
  { code: "PF", fallbackLabel: "French Polynesia" },
  { code: "PG", fallbackLabel: "Papua New Guinea" },
  { code: "PH", fallbackLabel: "Philippines" },
  { code: "PK", fallbackLabel: "Pakistan" },
  { code: "PL", fallbackLabel: "Poland" },
  { code: "PM", fallbackLabel: "St Pierre & Miquelon" },
  { code: "PN", fallbackLabel: "Pitcairn" },
  { code: "PR", fallbackLabel: "Puerto Rico" },
  { code: "PS", fallbackLabel: "Palestine" },
  { code: "PT", fallbackLabel: "Portugal" },
  { code: "PW", fallbackLabel: "Palau" },
  { code: "PY", fallbackLabel: "Paraguay" },
  { code: "QA", fallbackLabel: "Qatar" },
  { code: "RE", fallbackLabel: "Réunion" },
  { code: "RO", fallbackLabel: "Romania" },
  { code: "RS", fallbackLabel: "Serbia" },
  { code: "RU", fallbackLabel: "Russia" },
  { code: "RW", fallbackLabel: "Rwanda" },
  { code: "SA", fallbackLabel: "Saudi Arabia" },
  { code: "SB", fallbackLabel: "Solomon Islands" },
  { code: "SC", fallbackLabel: "Seychelles" },
  { code: "SD", fallbackLabel: "Sudan" },
  { code: "SE", fallbackLabel: "Sweden" },
  { code: "SG", fallbackLabel: "Singapore" },
  { code: "SH", fallbackLabel: "St Helena" },
  { code: "SI", fallbackLabel: "Slovenia" },
  { code: "SJ", fallbackLabel: "Svalbard & Jan Mayen" },
  { code: "SK", fallbackLabel: "Slovakia" },
  { code: "SL", fallbackLabel: "Sierra Leone" },
  { code: "SM", fallbackLabel: "San Marino" },
  { code: "SN", fallbackLabel: "Senegal" },
  { code: "SO", fallbackLabel: "Somalia" },
  { code: "SR", fallbackLabel: "Suriname" },
  { code: "SS", fallbackLabel: "South Sudan" },
  { code: "ST", fallbackLabel: "Sao Tome & Principe" },
  { code: "SV", fallbackLabel: "El Salvador" },
  { code: "SX", fallbackLabel: "St Maarten (Dutch)" },
  { code: "SY", fallbackLabel: "Syria" },
  { code: "SZ", fallbackLabel: "Eswatini (Swaziland)" },
  { code: "TC", fallbackLabel: "Turks & Caicos Is" },
  { code: "TD", fallbackLabel: "Chad" },
  { code: "TF", fallbackLabel: "French S. Terr." },
  { code: "TG", fallbackLabel: "Togo" },
  { code: "TH", fallbackLabel: "Thailand" },
  { code: "TJ", fallbackLabel: "Tajikistan" },
  { code: "TK", fallbackLabel: "Tokelau" },
  { code: "TL", fallbackLabel: "East Timor" },
  { code: "TM", fallbackLabel: "Turkmenistan" },
  { code: "TN", fallbackLabel: "Tunisia" },
  { code: "TO", fallbackLabel: "Tonga" },
  { code: "TR", fallbackLabel: "Turkey" },
  { code: "TT", fallbackLabel: "Trinidad & Tobago" },
  { code: "TV", fallbackLabel: "Tuvalu" },
  { code: "TW", fallbackLabel: "Taiwan" },
  { code: "TZ", fallbackLabel: "Tanzania" },
  { code: "UA", fallbackLabel: "Ukraine" },
  { code: "UG", fallbackLabel: "Uganda" },
  { code: "UM", fallbackLabel: "US minor outlying islands" },
  { code: "US", fallbackLabel: "United States" },
  { code: "UY", fallbackLabel: "Uruguay" },
  { code: "UZ", fallbackLabel: "Uzbekistan" },
  { code: "VA", fallbackLabel: "Vatican City" },
  { code: "VC", fallbackLabel: "St Vincent" },
  { code: "VE", fallbackLabel: "Venezuela" },
  { code: "VG", fallbackLabel: "Virgin Islands (UK)" },
  { code: "VI", fallbackLabel: "Virgin Islands (US)" },
  { code: "VN", fallbackLabel: "Vietnam" },
  { code: "VU", fallbackLabel: "Vanuatu" },
  { code: "WF", fallbackLabel: "Wallis & Futuna" },
  { code: "WS", fallbackLabel: "Samoa (western)" },
  { code: "YE", fallbackLabel: "Yemen" },
  { code: "YT", fallbackLabel: "Mayotte" },
  { code: "ZA", fallbackLabel: "South Africa" },
  { code: "ZM", fallbackLabel: "Zambia" },
  { code: "ZW", fallbackLabel: "Zimbabwe" },
];

const regionDisplayNames =
  typeof Intl !== "undefined" && typeof Intl.DisplayNames === "function"
    ? new Intl.DisplayNames(["pt-BR", "en"], { type: "region" })
    : null;

function getLocalizedRegionLabel(code: string, fallbackLabel: string) {
  if (!regionDisplayNames) {
    return fallbackLabel;
  }

  return regionDisplayNames.of(code) || fallbackLabel;
}

export const COUNTRY_OPTIONS: CountryOption[] = COUNTRY_SEED.map(
  ({ code, fallbackLabel }) => ({
    code,
    label: getLocalizedRegionLabel(code, fallbackLabel),
  }),
).sort((left, right) =>
  left.label.localeCompare(right.label, "pt-BR", { sensitivity: "base" }),
);
