# Generated by Django 5.0.1 on 2026-03-07 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_alter_doctorinvitation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("doctor", "Doctor")],
                        default="doctor",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenants_membership",
            },
        ),
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=255)),
                ("livemode", models.BooleanField(default=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tenants_stripe_webhook_event",
            },
        ),
        migrations.AddField(
            model_name="clinic",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("past_due", "Past due"),
                    ("canceled", "Canceled"),
                ],
                default="canceled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="plan_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("clinic", "Clinic")],
                default="clinic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="scheduled_seat_effective_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="scheduled_seat_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="stripe_current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="stripe_subscription_item_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="seat_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Seat limit mirrored from Stripe subscription item quantity.",
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("clinic_monthly", "Clinic monthly"),
                    ("clinic_yearly", "Clinic yearly"),
                ],
                default="free",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(
                fields=["stripe_customer_id"], name="tenants_cli_stripe__f7a2ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(
                fields=["stripe_subscription_id"], name="tenants_cli_stripe__f81bf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(
                fields=["account_status"], name="tenants_cli_account_9a55f5_idx"
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="tenants.clinic",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="stripewebhookevent",
            index=models.Index(
                fields=["event_type", "processed_at"],
                name="tenants_str_event_t_4de077_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["account", "role"], name="tenants_mem_account_481bb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["user"], name="tenants_mem_user_id_4fc6ba_idx"),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("account", "user"),
                name="tenants_membership_unique_account_user",
            ),
        ),
    ]
