# Generated by Django 5.0.1 on 2026-03-09 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_backfill_memberships_and_normalize_clinic_billing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="billing_grace_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SubscriptionEventLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("clinic", "Clinic"), ("individual", "Individual")],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("webhook", "Webhook"),
                            ("reconciliation", "Reconciliation"),
                        ],
                        default="webhook",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("event_type", models.CharField(max_length=255)),
                ("event_created_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPLIED", "Applied"),
                            ("IGNORED_STALE", "Ignored stale"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_event_ledger_entries",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_event_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenants_subscription_event_ledger",
                "indexes": [
                    models.Index(
                        fields=["object_type", "event_created_at"],
                        name="tenants_sub_object__24fec8_idx",
                    ),
                    models.Index(
                        fields=["clinic", "event_created_at"],
                        name="tenants_sub_clinic__7d7af9_idx",
                    ),
                    models.Index(
                        fields=["user", "event_created_at"],
                        name="tenants_sub_user_id_b383e9_idx",
                    ),
                    models.Index(
                        fields=["status", "processed_at"],
                        name="tenants_sub_status_60aceb_idx",
                    ),
                ],
            },
        ),
    ]
