# Generated by Django 5.0.1 on 2026-03-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_clinic_billing_grace_until_subscriptioneventledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
