# Generated by Django 5.0.1 on 2026-02-11 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SEEN", "Login Seen"),
                            ("STUDY_SUBMIT", "Study Submitted"),
                            ("STUDY_STATUS_CHECK", "Study Status Checked"),
                            ("RESULT_DOWNLOAD", "Result Downloaded"),
                            ("DOCTOR_INVITE", "Doctor Invited"),
                            ("DOCTOR_REMOVE", "Doctor Removed"),
                            ("CLINIC_CREATED", "Clinic Created"),
                            ("CLINIC_UPDATED", "Clinic Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of affected resource (study_id, user_id, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the action",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "timestamp"],
                        name="audit_audit_clinic__7abda4_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_audit_user_id_cc7aa2_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_audit_action_e47115_idx"
                    ),
                ],
            },
        ),
    ]
