# Generated by Django 5.0.1 on 2026-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SEEN", "Login Seen"),
                    ("STUDY_SUBMIT", "Study Submitted"),
                    ("STUDY_STATUS_CHECK", "Study Status Checked"),
                    ("RESULT_DOWNLOAD", "Result Downloaded"),
                    ("DOCTOR_INVITE", "Doctor Invited"),
                    ("DOCTOR_INVITE_CANCEL", "Doctor Invitation Canceled"),
                    ("DOCTOR_REMOVE", "Doctor Removed"),
                    ("CLINIC_CREATED", "Clinic Created"),
                    ("CLINIC_UPDATED", "Clinic Updated"),
                    ("BILLING_CHECKOUT_CREATED", "Billing Checkout Created"),
                    ("BILLING_SUBSCRIPTION_UPDATED", "Billing Subscription Updated"),
                    ("BILLING_PORTAL_OPENED", "Billing Portal Opened"),
                    ("BILLING_SYNCED", "Billing Synchronized"),
                    ("BILLING_SEATS_UPDATED", "Billing Seats Updated"),
                    ("BILLING_DOWNGRADE_SCHEDULED", "Billing Downgrade Scheduled"),
                    ("BILLING_DOWNGRADE_APPLIED", "Billing Downgrade Applied"),
                    ("BILLING_WEBHOOK_PROCESSED", "Billing Webhook Processed"),
                ],
                max_length=50,
            ),
        ),
    ]
